---
ci:
  autofix_commit_msg: 'style(pre-commit): auto fixes from pre-commit hooks'
  autofix_prs: true
  autoupdate_branch: main
  autoupdate_commit_msg: 'chore(deps): update pre-commit hooks'
  autoupdate_schedule: weekly
  skip:
    - ty-check
    - interrogate
    - deptry
    - vulture
    - xenon
    - sync-pre-commit-deps
  submodules: false
