StylesPath = .github/styles
MinAlertLevel = suggestion

Packages = Google, proselint

Vocab = findfmt

[*.md]
BasedOnStyles = Vale, Google, proselint

# Tailored rule configurations for technical CLI documentation
Google.Headings = NO
Google.WordList = NO
Google.Acronyms = NO
Google.Parens = NO
Google.Colons = NO
Google.OptionalPlurals = NO
Google.Latin = suggestion
Google.EmDash = suggestion
Google.Contractions = suggestion
Google.We = suggestion
Google.WordListCase = suggestion

# Token ignores: ignore URLs and inline links
TokenIgnores = (https?://[^\s]+)
